routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//ekhane nicher router namer oikhane >>> admin <<<hbe now for this direct page link;
Route::get('/', 'PublicController@index')->name('firstPage');

Route::get('/single/{post}', 'PublicController@singlePage')->name('singlePage');
Route::get('/category/{category}', 'PublicController@listPage')->name('listPage');
Route::get('/tag/{tag}', 'PublicController@listPage')->name('listPageTag');
Route::post('/content/{id}', 'CommentController')->name('comment');
Route::get('/video', 'PublicController@videoPage')->name('videoPage');
Route::get('/video/{video}', 'PublicController@videoDetails')->name('videoDetails');


Route::get('/admin', function () {
    return view('backend.home');
});


Route::get('/categories', 'CategoryController@index')->name('categories.index');
Route::get('/categories/trash', 'CategoryController@trash')->name('categories.trash');
Route::get('/categories/trash/{id}/restore', 'CategoryController@restore')->name('categories.restore');
Route::delete('/categories/trash/{id}/delete', 'CategoryController@delete')->name('categories.delete');

Route::get('categories/create', 'CategoryController@create')->name('categories.create');
Route::post('/categories', 'CategoryController@store')->name('categories.store');
Route::get('categories/{data}/edit', 'CategoryController@edit')->name('categories.edit');
Route::put('categories/{data}', 'CategoryController@update')->name('categories.update');

Route::get('categories/show/{data}', 'CategoryController@show')->name('categories.show');
Route::delete('categories/{data}', 'CategoryController@destroy')->name('categories.destroy');
//Route::get('categories/single', 'CategoriesController@show')->name('categories.single');
//Route::get('/admin', function () {
//    return view('backend.categories.index');
//});
//>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>for post<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Route::resource('posts','PostController');
Route::resource('tags','TagController');
Route::resource('videos','VideoController');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/backend/layouts/partials/footer.blade.php
<div class="copyright-w3layouts py-xl-3 py-2 mt-xl-5 mt-4 text-center">
    <p>© 2018 Modernize . All Rights Reserved | Design by
        <a href="http://w3layouts.com/"> W3layouts </a>
    </p>
</div>

resources/views/backend/layouts/partials/header.blade.php
<?php

resources/views/backend/layouts/partials/sidebar.blade.php
<div class="sidebar-header">
    <h1>
        <a href="index.html">{{ config('app.name') }}</a>
    </h1>
    <span>M</span>
</div>
<div class="profile-bg"></div>
<ul class="list-unstyled components">
    <li class="active">
        <a href="index.html">
            <i class="fas fa-th-large"></i>
            Dashboard
        </a>
    </li>
    <li>
        <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false">
            <i class="fas fa-laptop"></i>
            Categories
            <i class="fas fa-angle-down fa-pull-right"></i>
        </a>
        <ul class="collapse list-unstyled" id="homeSubmenu">
            <li>
                <a href="{{route('categories.create')}}">Add</a>
            </li>
            <li>
                <a href="{{route('categories.index')}}">List</a>
            </li>
        </ul>
    </li>

    <li>
        <a href="#tags" data-toggle="collapse" aria-expanded="false">
            <i class="fas fa-laptop"></i>
            Tags
            <i class="fas fa-angle-down fa-pull-right"></i>
        </a>
        <ul class="collapse list-unstyled" id="tags">
            <li>
                <a href="{{route('tags.create')}}">Add</a>
            </li>
            <li>
                <a href="{{route('tags.index')}}">List</a>
            </li>
        </ul>
    </li>



    <li>
        <a href="#posts" data-toggle="collapse" aria-expanded="false">
            <i class="fas fa-laptop"></i>
            Posts
            <i class="fas fa-angle-down fa-pull-right"></i>
        </a>
        <ul class="collapse list-unstyled" id="posts">
            <li>
                <a href="{{route('posts.create')}}">Add</a>
            </li>
            <li>
                <a href="{{route('posts.index')}}">List</a>
            </li>
        </ul>
    </li>
    <li>
        <a href="#videos" data-toggle="collapse" aria-expanded="false">
            <i class="fas fa-laptop"></i>
            Videos
            <i class="fas fa-angle-down fa-pull-right"></i>
        </a>
        <ul class="collapse list-unstyled" id="videos">
            <li>
                <a href="{{route('videos.create')}}">Add</a>
            </li>
            <li>
                <a href="{{route('videos.index')}}">List</a>
            </li>
        </ul>
    </li>

</ul>